### PR TITLE
License changes

### PR DESCRIPTION
**Pull request by skurhse**
- Add license section to README.
- Add MIT and Apache licenses.
- Remove MPL license.

### CODE REVIEW

**Comment by vprime** [comment]
I think Apache & MIT options are typically good for this sort of project.

**Comment by No767** [comment]
I haven't had time to contribute my opinion, but the question remains *why*? What advantages and disadvantages does this bring, and what opportunity costs are we making. Apache-2.0 ultimately is just a more legally verbose version of the MIT license if I recall.

In short, I am unsure of the decision and that's why I kept it on my tab but not approving the review

**Comment by skurhse** [comment]
> I haven't had time to contribute my opinion, but the question remains _why_? What advantages and disadvantages does this bring, and what opportunity costs are we making. Apache-2.0 ultimately is just a more legally verbose version of the MIT license if I recall.
> 
> In short, I am unsure of the decision and that's why I kept it on my tab but not approving the review

The dual licensing is a pragma I took from the rust crates template. It's meant to empower the user to have more licensing options.

**Comment by skurhse** [comment]
see: https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952

**Comment by No767** [comment]
> see: https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952

I actually read this already. but thanks

**Comment by skurhse** [comment]
here is the official answer: https://prev.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license

generally with licenses we want to go with a well-known, community-supported solution. I would personally be happy with just ASL2 if GPLv2 compatibility is not a concern. (probable)

**Pull request merged**
